### ISSUE TITLE
Feature request: To have more than one window running on small ccompetitions

### ISSUE THREAD

**Issue by sdaaish** [melinsoftware/meos#1]
When running a small competition on 1 computer, you would like to have 2 masters connected. One for registering competitors and 1 for reading out results at the same time. This works as it is (3.4.782), but the windows are overlapping. Ie you cannot see the results window because the register window is on top.

To recreate this you start "Quick entry mode" and "Readout/radio" from the Sportident tab.

If the windows where separated and not overlapping would be great. Either as free floating windows, or just as the "Services" work when you have more than one running at the same time.

**Comment by erikmelin** [comment]
@sdaaish You can use one computer and run two instances of MeOS if you want this. 

All master stations connected to MeOS will communicate with the active SI functionality, which means you only need one master station, if you are prepared to switch view depending on entry or readout. There is also interactive readout.
