### ISSUE TITLE
IOF Club export does not export ID

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#15]
If we create a runners/clubs database for our events, we export them between events with "Export Clubs/Persons (IOF-XML)" options.
The persons XML is exported having Organisation marked with ID:
```xml
<Competitor>
<Person>
<Name>
<Given>Māris</Given>
<Family>Zinbergs</Family>
</Name>
</Person>
<Organisation>
<Id>40</Id>
</Organisation>
</Competitor>
```
But clubs xml does not have this ID in the export:
```xml
<Organisation>
<Name>Siguldas Takas</Name>
</Organisation>
```
We are unable to use these XMLs for import as persons get assigned the wrong clubs.
If I add the <Id> manually to the exported club XML, the import works correctly.

**Comment by erikmelin** [comment]
I think rather the competitor export should be change to include the full club name in this case.
