### ISSUE TITLE
Draw start times - option to choose where to add the vacancies

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#19]
It would be great if we had better control of drawing start times for vakancies - vacancies as first/vacancies as last in group

**Comment by valdisj** [comment]
This is important enhancement, since Latvian Orienteering Feredation rules say, that vacancies should be in beginning of all events.

**Comment by erikmelin** [comment]
I'll try to fix this. But if you do not really want the vacant position drawn, it might bu better to not use vacancies, but do add the late entries manually first (or last) in the start list by simply adding them as a new competitor (and look in the start list for what start time to set).

**Comment by mariszin** [comment]
If I add the vacancy to the list manually, I have to check all other classes with the same distance so no 2 runners with the same distance start at the same time.

**Comment by erikmelin** [comment]
I do understand the need for this functionality. 

For now, when you draw the classes, you can set the "Reserved" field to a positive number (expected number of variances) in manual draw, several classes. MeOS will ensure this number of "free" positions before the first allocated start in the class.

**Comment by erikmelin** [comment]
Fixed.
