### ISSUE TITLE
Rental cards not used in interactive readout for unregistered cards

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#22]
During our weekly events, we don't have a registered start list. We use a precreated runners database, all readouts are interactive.
If we create a list of rental cards and then readout one such card, then
1) We do net get the message "Return rental card"
2) The card is not marked as "Borrowed" for this competitor

**Comment by erikmelin** [comment]
Right, this seems like a natural enhancement.

**Comment by mariszin** [comment]
We are having indoor O tomorow. We will be testing the latest  beta :)

**Comment by erikmelin** [comment]
Fixed now.
