### ISSUE TITLE
How to delay start times?

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#23]
When start times have been drawn and published, how to postpone them all for a fix amount of time (e.g. due to a control issue discovered just before the event or a weather alert)?

**Comment by kamilpipek** [comment]
Just change the "Zero time" on the page "Competition" and then in the dialog window choose "No".

**Comment by pgaufillet** [comment]
Thank you for your answer: it works nicely. It is just difficult to find how to proceed.
What about a button "Shift start times" on the competition page or maybe (integrated) documentation about it?

**Comment by erikmelin** [comment]
The suggested method is documented. I think this is enough for now.
