### ISSUE TITLE
Config printer layout with results of previous finishers

### ISSUE THREAD

**Issue by valdisj** [melinsoftware/meos#25]
Suggest an improvement into how printer prints result slip.
When slip is printed, then MEOS to look in current standings of finishers and print out first 3 places with details, and then my result. Attached is example:
![IMG_6945](https://user-images.githubusercontent.com/5184678/66257994-87c70580-e7a8-11e9-8fa0-c5d6acce11d5.jpg)

**Comment by erikmelin** [comment]
Thanks for the suggestion.

**Comment by valdisj** [comment]
Hi Erik,
Do you believe, this could be done to add to the release?
We have been trying to play with Custom Text Fields in Printer, but those does not seem to work, since no such option to print winner name and winner time exists.

**Comment by erikmelin** [comment]
@valdisj A more customizable split print layout is high priority. I am thinking about it.
