### ISSUE TITLE
Startlist times published to Eventor may be corrupt in GMT+ locations

### ISSUE THREAD

**Issue by undyau** [melinsoftware/meos#28]
The calculation of GMT start times can go wrong in ```oEvent::getAbsDateTimeISO``` if the time-zone offset is greater than the start time. Example - start time 10:34:00, location GMT + 11.

This code assumes that ```t``` is signed, but it is declared as DWORD. 
``` C++
      int offset = ::getTimeZoneInfo(Date);
      t += offset;
      if (t < 0) {
        extraDay = -1;
        t += 3600 * 24;
      }
      else {
        extraDay = t / (3600*24);
      }
```
Changing declaration to ```unsigned long t;``` fixes this I think.

**Comment by erikmelin** [comment]
Thanks for spotting this; it is easily missed when you live close to GMT. Fixed.
