### ISSUE TITLE
Settings are not all available after new installations of MeOS

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#29]
When MeOS is started for the first time, most settings are not available in `Change local settings...`

The workaround is to open an event and display once each thumbnail (runners, lists, etc.).

But it would be nice to initialize the list of parameters at installation time.

**Comment by erikmelin** [comment]
This is by design to simplify administration/distribution. Are there any parameters that you think are more important than others? I could try to fix those.

**Comment by pgaufillet** [comment]
Unsurprizingly _NameMode_ is the one I would recommend to always display :-)

**Comment by erikmelin** [comment]
The most important properties are now present.
