### ISSUE TITLE
Missing sentence in language file

### ISSUE THREAD

**Issue by jmonclard** [melinsoftware/meos#3]
A user (Patrice Lavallee) reported me that the following error message has been displayed to him in Swedish:
*Ett okänt fel inträffade*

This sentence isn't in the language file (at least not in the english, german and french one).
It can be found in the following C++ files : 
* autotask.cpp (on lines 77, 130, 282 and 301)
* download.cpp (on line 313)
* gdioutput.cpp (on lines 759, 1960, 1963, 2167, 2170, 2695, 2698, 2752, 2755, 2790, 2793, 5637 and 5640)
* TabAuto.cpp (on line 172)
* TabSI.cpp (on line 1712)

It need probably be added to the language files.
Google translate gave me *"An unknown error occurred"*. If this is correct, it will be translated in french as *"Une erreur inconnue s'est produite"*.

**Comment by erikmelin** [comment]
Fixed.
