### ISSUE TITLE
How to set up mandatory controls for all members without order in team rogaining event?

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#30]
Hi,

I have defined a rogaining event for teams of 3 runners. They starts simultaneously and the time of the team is the time of the last runner. But I don't see how to set 4 mandatory controls for all 3 runners without imposing their order.

Any hint? :-)

**Comment by kamilpipek** [comment]
For mandatory control you can use status Multiple instead of Rogaining and all of these them MUST be visited in any order.

**Comment by kamilpipek** [comment]
![191115-meos-multiplecontrol](https://user-images.githubusercontent.com/40379351/68930590-01321a80-078f-11ea-9f16-f5f9b3771b5e.png)

**Comment by pgaufillet** [comment]
Understood! Thanks @kamilpipek
