### ISSUE TITLE
[Rogaining] Allow less than 1 point/minute of penalty

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#31]
The rule of the rogaining event I am configuring is 1 point of penalty / 4 minutes. But it seems MeOS 3.6 only supports integer number of points / minutes: so the minimum is 1 point / minute. 

Is there a way to specify a such thing?

**Comment by kamilpipek** [comment]
Seems to me you are right. But my opinion is that you can in relative simply write your own Result module (or modify an existing template) with modified Point calculation for team according to your requirements.

**Comment by pgaufillet** [comment]
Good suggestion. Yet another facet of MeOS I have not explored. :-)
I keep this ticket open anyway, as it seems something might be implemented.

**Comment by erikmelin** [comment]
I have no plans to change the basic type of score points to anything else than integers. You can achieve the same effect by multiplying your score by 4, 100, or some other integer. It is possible to use result modules to format output as a decimal number, if desired.
