### ISSUE TITLE
Support HTTP(S) for downloading runners/clubs databases

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#33]
For now, it is required to download manually the CSV or XML files and then import them in MeOS.
Supporting HTTP/HTTPS protocols would make it 'one-click' operation.
The default URL may be configured as a local setting. Almost no UI change is required: the field Filename IOF... shall just be adapted and the behaviour can be adapted by detecting "http"/"https" at the beginning of the path.

**Comment by erikmelin** [comment]
Seems like an easy feature to add.

**Comment by erikmelin** [comment]
Registered this as a suggested project.
