### ISSUE TITLE
Full screen (page by page) list view is partially broken

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#34]
The font size sometimes suddenly changes during display to huge or tiny characters.
The space between lines is sometimes too large.

It seems to happen especially when several monitors are used with different dpi.

**Comment by erikmelin** [comment]
I need a clear reproduce to investigate. I have not been able to reproduce the issue with one external monitor attached to a laptop.

**Comment by pgaufillet** [comment]
Hi Erik,

you can reproduce the configuration leading to this issue by enabling 2 displays in a Virtualbox Windows 10 VM. Configure the main display with scale factor = 200%, and the secondary display with scale factor = 100%.

Just in case it plays a role, the other parameters are Video mem=256M, graphic controller=VBoxSVGA, Acceleration=3D, VirtualBox 6.1.4, latest update of Windows 10.

**Comment by erikmelin** [comment]
Hopefully works now.
