### ISSUE TITLE
SportIdent should disconnect when closing the competition

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#35]
If I do not disconnect the SI reader before closing the competition, when I open the next one, Autosearch will not find any available SI reader.
It is also not possible to disconnect from software the SI reader after closing the event. I have to close the app or disconnect reader from PC to be able to connect to it again.

**Comment by erikmelin** [comment]
The indented design is to keep SI connection open between competitions. And you can close it by going to tab SI (which is open after competition is closed), and if you open a new competition, the SI connection is still open (so you cannot open it again, just continue reading cards.) This seems to work.

**Comment by mariszin** [comment]
If so, it should show the connection as active, when opening a new competition. 
Right now, it does not show "Disconnect" button - just "Activate"

**Comment by erikmelin** [comment]
It depends on which COM port you select from the drop down. You could use several SI units, and those connected shows an [OK] after the name.

**Comment by mariszin** [comment]
Ok, checked once again with a reader - it does show "OK" next to the COM port, and "Disconnect" button for that port.
