### ISSUE TITLE
Message box on silent readout does not show if the card used is rental

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#37]
As there are times You have to do other things with MeOS, while the cards are being read out, it would be nice if the small popup window would show some info, if the card is borrowed and should be returned.
The relevant place in code:
https://github.com/melinsoftware/meos/blob/338fb3c34ecbc8c72c5419dcbca656f548984222/code/TabSI.cpp#L2615-L2642

**Comment by erikmelin** [comment]
Support added in MeOS 4.1
