### ISSUE TITLE
After uploading local competition to database, that instance of MeOS doesn't sync

### ISSUE THREAD

**Issue by undyau** [melinsoftware/meos#41]
After uploading a local competition to database, changes to competitors made on other clients connected to the database are not showing on the original MeOS instance unless that instance disconnects/reconnects to the competition on the server.  

It looks as though the problem is that the `updated` timestamp in the `SqlUpdated` structure is still an empty string at the time that it is used to form a query in `MeosSQL::selectUpdated`. When the query created is used, the timestamp is invalid and no new data is retrieved for the list from the database.

My simple fix was to alter the query generated in `MeosSQL::selectUpdated` if the `updated` member was empty, but there is probably a better way to address this.

**Comment by erikmelin** [comment]
Fixed.
