### ISSUE TITLE
The "Behind" calculation is not correct in multi-stage total results

### ISSUE THREAD

**Issue by epkjoja** [melinsoftware/meos#42]
As can be seen in this Total results report the "Efter" (Behind) column is not correctly calculated.
https://eventor.orientering.se/Documents/Event/72102/Totalresultat

The value always seems to be one second longer than the actual total time.
Example:
```
H80 (12 / 12)                         Totaltid  Efter       Etapp             Bomtid
1. Anders Carlsson Skåneslättens OL   2:04:37   +124:38     38:13 1.  04:48
2. Raimo Salminen OK Pan-Kristianstad 2:15:04   +135:05     41:53 3.  +3:40   04:50
```

**Comment by kamilpipek** [comment]
Hi Erik, we have now with the 3.8 Beta the same experience the Total Time After is in our case calculated as Total Time +1s.
![obrazek](https://user-images.githubusercontent.com/40379351/131217794-64777b3b-eabc-443f-a823-165b4003f68c.png)

**Comment by kamilpipek** [comment]
The problem is there since Version 3.7.1188 RC2. All previous revisions including Version 3.7.1178 RC1 seems to be OK.

**Comment by erikmelin** [comment]
Fixed.
