### ISSUE TITLE
MOP: Course info sporadically provided

### ISSUE THREAD

**Issue by alberthatesnewsletters** [melinsoftware/meos#48]
Refreshing http://localhost:2009/meos?difference=zero means that classes and runners sometimes tell me what course they are using, sometimes not.

**With:**
```
<cls id="2" ord="20" radio="142" crs="2">Medium</cls>
<cmp id="1" card="500114">
<base org="14" cls="1" stat="1" st="651600" rt="25680" crs="1">Hans Persson</base>
<input it="0" tstat="1"/>
</cmp>
```

**Without:**
```
<cls id="2" ord="20" radio="142">Medium</cls>
<cmp id="1" card="500114">
<base org="14" cls="1" stat="1" st="651600" rt="25680">Hans Persson</base>
<input it="0" tstat="1"/>
</cmp>
```

Either the whole file contains course info (where applicable), or none of it does.

I (currently) have no use for course info, so for me this is merely inconsistent behavior, not problematic.

**Comment by erikmelin** [comment]
@alberthatesnewsletters Thanks for reporting. Fixed in source.
