### ISSUE TITLE
MOP: Adding a new class elicits no reaction

### ISSUE THREAD

**Issue by alberthatesnewsletters** [melinsoftware/meos#49]
If I delete a class, MOP will straight up send a MOPComplete in the next update. If I add a class, nothing happens; the next difference doesn't show it. If I add a new runner, and assign them as the first runner of this new class, the update will say this runner was deleted.

**Comment by erikmelin** [comment]
@alberthatesnewsletters The reason for this is that the class selection (of the service) does not include that new class. It seems reasonable to automatically extend this selection at least if all classes were selected initially.
