### ISSUE TITLE
 Had to validate class/category for almost all runners during event

### ISSUE THREAD

**Issue by bagage** [melinsoftware/meos#5]
I'm not sure if this is some kind of misconfiguration or a bug in MeOS, but this weekend Meos did not recognized almost 90% of runners' course when their SI unit was read - I had to manually select the class they ran.
It worked fine on Saturday where I had 3 courses (A1,A2,B) with 3 associated classes (A1,A2,B), but Sunday it failed with a similar setup but more courses (say A1,A2,B but also variant A1, variant A2, variant B) and again 6 classes associated _but not with the exact same name_ (say first A1, first A2, first B, second A1, second A2, second B).

I thought that MeOS would smartly match the class/course with the best match given the controls read on the SI Unit?

**Comment by erikmelin** [comment]
A reproduce / copy of the competition is needed to analyze this any further. And info on what card data was read out and what happened.

**Comment by bagage** [comment]
@erikmelin Is their an email address to which I can send the exported competitions data (I exported XML, would it be enough?)? I'd rather not publish them here. Thanks!

**Comment by erikmelin** [comment]
@bagage, Please use software@melin.nu.

**Comment by bagage** [comment]
Email sent!

**Comment by erikmelin** [comment]
@bagage this works as designed. MeOS will select class for a new runner based on the course, or for a class with a course pool select the right course from the pool. But never change class for an existing runner based on what course she took.
