### ISSUE TITLE
Content-Type header is incorrectly set if the content is smaller than 1024 bytes while zip is enabled

### ISSUE THREAD

**Issue by Lucke0051** [melinsoftware/meos#50]
When uploading online results, if zip is enabled and the XML size is smaller than 1024 bytes, it will still send the ``application/zip`` content header.

Fix: Ensure that the if statement at 438 (onlineresults.cpp) checks if the file will be sent as raw XML even though zip is enabled.

**Comment by erikmelin** [comment]
Thanks for the report @Lucke0051 . Fixed in source.
