### ISSUE TITLE
Compile and run under linux

### ISSUE THREAD

**Issue by bammitzb** [melinsoftware/meos#51]
What will it take to compile and run this under linux? I can help with the task if it is not too big an effort.

**Comment by jmonclard** [comment]
Having Meos running natively under Linux would be great. But FYI it runs pretty well with Wine (I haven't tested all features but haven't had an issue yet).

**Comment by bammitzb** [comment]
I did a git clone and looked at the code. Actually tried to do a Makefile for it and I can unfortunately see a lot of work is needed. Too much of the code seems to be very windows centric and not very portable.
But as you write the win exe can run well under Wine, so if that works I will just try and use it like that.

**Comment by erikmelin** [comment]
Yes. Since MeOS is written directly for the Windows API it would be quite a lot of work to port it. Most of the API code is in gdiouput and in the startup code, so it is rather centralized. But still it would be a huge effort.
