### ISSUE TITLE
Documentation for requests of the MeOS Online Protocol XML 2.0

### ISSUE THREAD

**Issue by otahirs** [melinsoftware/meos#52]
Results Online Services sends multiple requests if response is not received in one second. 
Lets say the accepting server do some heavy lifting with incoming data and it takes 2.5 seconds to respond with OK status.  
Current behavior works like this.

```
time  |    MeOS                    |     Server
---------------------------------------------------
0s    |  FIRST request is send     |  working on FIRST request
1s    |  SECOND request is send    |  working on FIRST and SECOND request
2s    |  THIRD request is send     |  working on FIRST, SECOND and receiving THIRD  request
2.1s  |                            |  FIRST request done, sending OK  
2.2s  |    receives OK,            |  THIRD request payload is cut in the middle, only part of the XML is received
            THIRD request stops
```

There can be workarounds (and maybe only release build or query optimization can solve this issue for me, as all it take is to send reply under second). However, I think the current behavior is sub-optimal.

**Comment by otahirs** [comment]
After more debugging, I found out the data is send in multiple request and my previous assumptions were false.
```
Fire request: 83, MOPComplete, content length: 25067
Done request: 83
Fire request: 81, MOPDiff, content length: 51118
Done request: 81
Fire request: 99, MOPDiff, content length: 51326
Done request: 99
Fire request: 63, MOPDiff, content length: 51564
Done request: 63
Fire request: 75, MOPDiff, content length: 35277
Done request: 75
```

Is there a documentation i missed on using the MOP 2.0?

**Comment by erikmelin** [comment]
@otahirs I think this is quite well documented. First MeOS sends MOPComplete and then one or more MOPDiff. The typical reason for a MOPDiff is that you have changed something. But MeOS also does this to prevent too large requests when uploading a competition. This is not documented in the protocol, but if you support both complete and diff (which you need to), than it does not matter. I don't think a request will be sent until MeOS gets OK on the previous. Right?

I can add a remark about this.

**Comment by otahirs** [comment]
As I was implementing the protocol, I used MeOS to generate the requests. I was unaware that MeOS splits the requests and falsely deduced, by glancing at the code, that MeOS must resend the request.   
MOP is well documented, but this missing bit sent me to a shallow rabbit hole. I am parsing `MOPComplete` and `MOPDiff `using the same logic (and the implementation was not complete yet), so until I logged which document is processed, I was a little bit confused what is going on.  

You could add a remark that MeOs service's `MOPComplete` can be accompanied by (multiple) following `MOPDiff` requests, if the payload is to big.

Big thanks for documenting the protocol in the first place, it enable us to tightly integrate MeOS with our [OResults](https://oresults.eu) platform (live results + radio controls).
