### ISSUE TITLE
Missing <Id> in IOF XML exports

### ISSUE THREAD

**Issue by otahirs** [melinsoftware/meos#53]
iof xml exports (startlist, resultslist) are missing the Id for person.  
it it important to be able to properly map information exported using MeOS Online Protocol with documents exported as IOF XML
```xml
<Person>
	<Id>42</Id> <!-- missing -->
	<Name>
		<Family>Hirs</Family>
		<Given>Otakar</Given>
	</Name>
</Person>
```

**Comment by erikmelin** [comment]
The Id is included, provided you have set the external Id for the person. MeOS will not export its internal Id since it is of little interest. If you import from IOF-XML with an Id, the external Id is set automatically.
