### ISSUE TITLE
Rogaining Course not maintained when importing event

### ISSUE THREAD

**Issue by mkozma** [melinsoftware/meos#55]
Environment: MEOS-OZ version 3.8.1306.1

When importing an import, previously saved as a meos backup which contains a course which has rogaining score controls, the course comes through as [From class] without the course name at the the beginning.

This means results won't contain the rogaining points.
See attached:
![Meos - Rogaining course import issue](https://user-images.githubusercontent.com/7262325/225203632-4ca0b8c1-36cd-43c1-a111-a2c4597d96c1.png)

Workaround:
Manually set course to the correct course for each competitor on the rogaining course and save (Click off and then on again)
Course controls now appear in right hand box and points in results.

Thanks for all your work.
Regards,
Martin Kozma
Bayside Kangaroos Orienteering Club

**Comment by erikmelin** [comment]
Seems like a user error.
