### ISSUE TITLE
Meos Build Instructions

### ISSUE THREAD

**Issue by mkozma** [melinsoftware/meos#56]
Hi guys, I can see that there is a comment in the resources section of the website: 
"You can build MeOS in Visual Studio 2008 or 2010. We plan to publish some instructions soon."
Would it possible to get the details of this updated on the page please?

**Comment by erikmelin** [comment]
Thanks. That instruction is pretty outdated and I removed it. The new instruction is on the download page. Open the project and build in Visual Studio 2019 or later. You can use version 2022, but you have to install v142 platform toolset (or retarget)
