### ISSUE TITLE
Installer for 3.9.1437 (64 bit) corrupted?

### ISSUE THREAD

**Issue by Lucke0051** [melinsoftware/meos#57]
Every time I download the MeOSV39u1_64.exe installer, I get an NSIS integrity check error. This does not happen with previous versions. I can install the MeOSV39_64.exe version, which works just fine.
![image](https://github.com/melinsoftware/meos/assets/30857678/4e0ccec1-27b4-4ab4-9e4c-c2d028abf3dc)

**Comment by erikmelin** [comment]
Cannot reproduce.
