### ISSUE TITLE
Custom text field in quick entry

### ISSUE THREAD

**Issue by mkozma** [melinsoftware/meos#58]
We need an extra field in quick entry to record car registration numbers so that organisers can check if there are remaining participants still not accounted for.
The text field could be used for anything. Car registration or mobile mumber etc.
The text field could be optional (local settings)
This would allow us to process the many EODs (Enter on the days) without having the participant to go to registration desk to provide this information.
Thanks for all your work.
Cheers,
Martin Kozma
Bayside Kangaroos Orienteetring Club

**Comment by erikmelin** [comment]
Added in MeOS 4.0

**Comment by mkozma** [comment]
Hi Erik, firstly, thanks for all your work supporting the orienteering community. In regards to the Quick Entry I have been trying to understand how to use the 2 new data fields in the (Services - Information Server) Quick Entry.
![Screenshot_20240405_213302_Edge](https://github.com/melinsoftware/meos/assets/7262325/a7188074-f69c-4895-bcd8-bdf8a6c30c24)
Maybe just need doc updating.

Regards,
Martin

**Comment by erikmelin** [comment]
@mkozma No, custom data fields are not supported here. The web form is actually stored in "entryform.template" which you can edit. It uses MeOS Input Protocol (MIP) which in itself currently does not support all options, but some of them.

We could consider adding more datafields to MIP, and also publish alternative versions of entryform.template, but I would need to understand what options are needed.

**Comment by mkozma** [comment]
Erik,
Just one field to add the phone number into entryform.template should be enough. 
MIP allows quick entry without the database, and therefore a simpler setup. 
With long enter on the day queues, we need to be able to track people in the forest who bypass the finish, people who don't return hire sticks and general follow up information.
Many thanks,
Martin

**Comment by jmonclard** [comment]
Erik, if you are at it, on our side we would like to have sex and birth year.
Jérôme

**Comment by erikmelin** [comment]
@jmonclard @mkozma This is too late for version 4.0. I have added the request. MIP support birthdate, so that would be easy (you can add it yourself by modifying entryform.template. For the rest, and extension of MIP is first needed.
