### ISSUE TITLE
Remember hidden & re-ordered columns of Table Mode

### ISSUE THREAD

**Issue by mkozma** [melinsoftware/meos#64]
Remember hidden & re-ordered columns of Table Mode in a competition save. However, this would then require a new button somewhere to un-hide all columns.

**Comment by erikmelin** [comment]
I am not sure about this (but of course it could be useful sometimes). Since more people could work with the same table on different computers, it cannot be stored in the competition. Maybe local (per competition?), or possibly an named list of preconfigured/saved views.
