### ISSUE TITLE
A box in custom list properties where the path to a CSS file for generated HTML can be placed

### ISSUE THREAD

**Issue by mkozma** [melinsoftware/meos#66]
A box in custom list properties where the path to a CSS file for generated HTML can be placed.

**Comment by erikmelin** [comment]
A reasonable enhancement suggestion.

**Comment by scrupeus** [comment]
Perhaps make it a more generic "text to include in HTML head element" entry box?

This would allow users to include any combination of:
- custom CSS
- links to one or more stylesheets
- JS scripts
- links to one or more JS files
- metadata
- etc

**Comment by erikmelin** [comment]
This is actually available, by adding .template files to the MeOS data folder or installation. See for example columns.template in the installation folder.

In the next version, I will expose this functionality in MeOS (and improve on the syntax of the template files)
