### ISSUE TITLE
SI Readout window customization/colors

### ISSUE THREAD

**Issue by crcfree** [melinsoftware/meos#68]
The SI readout windows is a great feature, however the colors are very hard to see in bright daylight.
Stronger green/red colors, or the possibility to customize the window would help.
Also include the runners status as text, ei "OK", "Missing Punch" ..

Further, the notification about rental SI card is in swedish, when MeOS language is Danish.

**Comment by erikmelin** [comment]
The translation issue seems fixed and the status is included.

Further customization is not planned at the moment.
