### ISSUE TITLE
Relay team members have wrong forkings assigned after importing entry updates

### ISSUE THREAD

**Issue by timschro** [melinsoftware/meos#70]
### Background

In Germany we use an online entry system called [OManager](https://omanager.o-sport.de/) in which also the line up for relay events is managed. Clubs can change the line up until the respective deadline before the competition (usually the evening before the race). The tool exports entries as IOF XML. It is necessary to import the entries at least twice: First time when the starting list is "drawn" and the bib numbers are assigned, second time after the final line up deadline.

### Prerequisites

- Relay competition is set up
- Teams are imported (via IOF XML), partially also including line up
- Courses with forkings are imported and correctly assigned to teams (via bib number)

### Current behaviour

- After importing changed entries (IOF XML), the correct line up is reflected in MeOS (same as in imported XML)
- Team members who were already part of a team and now got another position (or another team) still have the _previously_ assigned forking assigned (which is now wrong)
- Team members who are newly added are assigned the correct forking according to the bib number and position in the team
- When changing positions via MeOS interface, the correct forkings are assigned  according to the bib number and position in the team

### Expected behaviour

- All team members always have the course / forking assigned as configured for the respective team (bib number and position in the team)
- The courses / forkings do not "follow" the runners

If necessary I can provide detailed examples.

**Comment by erikmelin** [comment]
Will be fixed in MeOS 4.0
