### ISSUE TITLE
Feature Request: Warn if the SI stick capacity is less than the number of controls in the course.

### ISSUE THREAD

**Issue by taaaaaad** [melinsoftware/meos#71]
We have a mixed pool of rental sticks, some SI5, SI8(capacity 30 punches) and SI9 (capacity 50 punches).  It would be nice to provide a warning when an assigned stick doesn't have the capacity for the course selected. 

You can easily determine the stick capacity by it serial number range, per this chart:
https://www.sportident.co.uk/information_sheets/SPORTident-CardComparison.PDF

**Comment by erikmelin** [comment]
Thanks for the suggestion.

**Comment by erikmelin** [comment]
Registered as a suggested project
