### ISSUE TITLE
MOP export of duplicate controls is undocumented

### ISSUE THREAD

**Issue by otahirs** [melinsoftware/meos#72]
If a competition has some online control duplicated, see example below:
![image](https://github.com/melinsoftware/meos/assets/24588500/4880bf41-7eb3-42f5-af68-195ed1caddc1)

it ends up in the _MeOS Online Protocol XML 2.0_ in this format:
`<radio>85,9130;100,11130;100100,16770</radio>`
the second control code is doubled end exported as **100100**

I would like to implement support for import of duplicated course controls from MeOS to [OResults](https://oresults.eu). 

Wouldn't it make more sense to export is as `<radio>85,9130;100,11130;100,16770</radio>`?
Or is this expected bahaviour that will stay as it is and I shall do some quirky error prone parsing?

**Comment by erikmelin** [comment]
The radio is merely an id (as documented), an refers to the control element <ctrl id="100100">100-2</ctrl> which would also be present in the export. You need to use that information (and not try to reverse engineer the Id). The name of the radio is user specified.
