### ISSUE TITLE
V4.0B1: Abort called when starting Info Server (with database)

### ISSUE THREAD

**Issue by erict-powersoft** [melinsoftware/meos#75]
I thought I had this working at one point [I tested my addition about zerotime (see pull request) only with local file - not mysql], but now it consistently and always causes an abort().  The last line I can set a breakpoint at is restserver.cpp:151.  Even when run in release mode the program just disappears shortly after starting the info server.

**Comment by erict-powersoft** [comment]
Never mind.  Seems port 2009 was somehow blocked.  Rebooting solved it.  Only argument could be that that an error message should be shown.  I'll try to come up with something and present as a pull request.

**Comment by erikmelin** [comment]
So far I have not been able to reproduce this.
