### ISSUE TITLE
Could paginating lists be the same HTML formatting as structured lists? 

### ISSUE THREAD

**Issue by bruceperson** [melinsoftware/meos#82]
Currently there are 4 possible formats for HTML lists:
1/ Unstructured single page
2/ Structured single page
3/ Paginating with header
4/ Paginating with no header

The structured HTML format uses tables, and has more hooks in it that CSS can work with. Ideally it would be better if the same CSS could be used for both structured and paginating pages, so the same structured format is used within paginating pages.
In that case a paginating structured output could always be employed; it only actually starts paginating once the page line limit is reached. If the default page line limit is infinite, it becomes just structured.   

Related to issues #65 and #66

**Comment by erikmelin** [comment]
I am afraid this will probably not happen.
