### ISSUE TITLE
E-punch reuse

### ISSUE THREAD

**Issue by vasyaabr** [melinsoftware/meos#9]
Sometimes, when reading data from e-punch on finish for athlete (1), MeOS tell me that this e-punch is for another athlete (2) (who actually finished), and ask to choose the group. There is no "Cancel" button to prevent this, thus we rewrite results for (2) with data from e-punch of (1). Usually, this happens when we cycle e-punchs (reuse them after clearing). Why this occur, and how to prevent this behavior?
Thanks!

**Comment by erikmelin** [comment]
This issue will be fixed by the next release, if I understand the problem description correctly.
